## lets start numpy

In [2]:
import numpy as np

In [4]:
arr_1 = np.array([1,2,3,4])
print(arr_1)
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

[1 2 3 4]


array([[1, 2, 3],
       [4, 5, 6]])

## multiplication | List vs np array

In [5]:
py_list=[1,2,3]
print(py_list *2)
np_array = np.array([1,2,3])
print(np_array * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


## some basic functions

In [ ]:
zero = np.zeros((2,3))
print(zero)

ones = np.ones((2,3))
print(ones)

full = np.full((2,4), 8)
print(full)

random = np.random.random((2,4))
print(random)
print(random*10)

round = np.round(random)
print(round)

arange = np.arange(0,10,2) ## equal gap between the raange
print(arange)

ln_space = np.linspace(0,100,15) ##equally spaced array within the range given
print(ln_space)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8 8]
 [8 8 8 8]]
[[0.12058584 0.8697005  0.23706048 0.17798584]
 [0.03165984 0.53722243 0.07538907 0.30962335]]
[[1.20585836 8.69700501 2.37060478 1.77985841]
 [0.31659837 5.37222431 0.75389075 3.09623347]]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]
[0 2 4 6 8]
[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


## types of array


In [ ]:
arr_1d = np.array([1,2,3])
print(f"arr_1d : {arr_1d}")

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(f"arr_2d : {arr_2d}")

arr_3d = np.array([[[1,2,3],
                    [4,5,6]],
                    [[1,2,3],
                     [4,5,6]]])
print(f"arr_3d : {arr_3d}")

arr_1d : [1 2 3]
arr_2d : [[1 2 3]
 [4 5 6]]
arr_3d : [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## array properties

In [30]:
arr = np.array([[1,2,3],
                   [4,5,6]])

print("shape : " , arr.shape) ## no of rows and columns
print("size" , arr.size) ## no of elements in matrix
print("Dtype :" , arr.dtype) ## data type inside it
print("dimension :" , arr.ndim) ## dimension of array

shape :  (2, 3)
size 6
Dtype : int64
dimension : 2


## resizing matrices

In [38]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3,4) ## to change the dimensions of the matrices
print(reshaped)

flatten = reshaped.flatten() ## FLATENS THE MATRIC IN 1D
print(flatten)
print(reshaped)

ravel = reshaped.ravel() ## returns a view instead of copy | might change original array
print(ravel)
print(reshaped)

trans = reshaped.transpose()
print(trans)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
