In [1]:
import numpy as np




In [2]:
# DATA STRUCTURE : [Restaurant_id,2022,2023,2024,2025]
sales_data = np.array([
    [1,200000,1500000,6000000,8900000],
    [2,340000,5700000,6800000,9700000],
    [3,450000,6700000,8200000,1000000],
    [4,120000,2300000,4500000,3100000],
    [5,900000,7600000,5000000,3400000]
])

In [3]:
print(sales_data.shape)

(5, 5)


## top 3 restaurant

In [4]:
print("Top 3 : ", sales_data[:3])

Top 3 :  [[      1  200000 1500000 6000000 8900000]
 [      2  340000 5700000 6800000 9700000]
 [      3  450000 6700000 8200000 1000000]]


In [7]:
total_sales_each_restaurant = np.sum(sales_data[:,1:], axis=1)
print("total sales of each restaurant : ",  total_sales_each_restaurant)

total sales of each restaurant :  [16600000 22540000 16350000 10020000 16900000]


In [8]:
total_sales_ofAll_restaurant_yearly = np.sum(sales_data[:,1:],axis=0)
print(total_sales_ofAll_restaurant_yearly)

[ 2010000 23800000 30500000 26100000]


In [10]:
# MINIMUM SALES OF A RESTAURANT

min_sales = np.min(sales_data[:,1:], axis = 1)
print("min sales of restaurant throghout years : " , min_sales)

## MAX SALES
max_sales = np.max(sales_data[:,1:], axis = 1)
print("max sales of restaurant throghout years : " , max_sales)

min sales of restaurant throghout years :  [200000 340000 450000 120000 900000]
max sales of restaurant throghout years :  [8900000 9700000 8200000 4500000 7600000]


In [12]:
# max sales among restaurant yearly
max_sales_among_all_rest_yearly = np.max(sales_data[:,1:],axis=0)
print(max_sales_among_all_rest_yearly)

# min sales among restaurant yearly
min_sales_among_all_rest_yearly = np.min(sales_data[:,1:],axis=0)
print(min_sales_among_all_rest_yearly)


[ 900000 7600000 8200000 9700000]
[ 120000 1500000 4500000 1000000]


In [14]:
# average sales per restaurant
avg= np.mean(sales_data[:,1:], axis=1)
print(avg)

# average sales of all restaurant yearly
avg_2= np.mean(sales_data[:,1:], axis=0)
print(avg_2)

[4150000. 5635000. 4087500. 2505000. 4225000.]
[ 402000. 4760000. 6100000. 5220000.]
