In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing :",arr[2:8])
print("WITH STEP :",arr[2:8:2])
print("negative indexing :",arr[-3])

basic slicing : [3 4 5 6 7 8]
WITH STEP : [3 5 7]
negative indexing : 8


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element" , arr_2d[1,1])
print("entire row" , arr_2d[2])
print("entire column" , arr_2d[:, 2])

specific element 5
entire row [7 8 9]
entire column [3 6 9]


## sorting

In [10]:
arr = np.array([2,5,8,9,4,2,1,3,7])
print("sorted array : ", np.sort(arr))

arr_2d = np.array([[1,4,6],[4,7,9],[1,8,2]])
print("sorted array with column: ", np.sort(arr_2d,axis=0))
print("sorted array with row: ", np.sort(arr_2d,axis=1))

sorted array :  [1 2 2 3 4 5 7 8 9]
sorted array with column:  [[1 4 2]
 [1 7 6]
 [4 8 9]]
sorted array with row:  [[1 4 6]
 [4 7 9]
 [1 2 8]]


## filters


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_num= arr[arr % 2 == 0]
print("filtered value :" , even_num)

filtered value : [ 2  4  6  8 10]


## mask with filter



In [12]:
mask = arr > 5
print("num greater than 5 :" , arr[mask])

num greater than 5 : [ 6  7  8  9 10]


## fancyindexing and np.where

In [14]:
index = [1,3,5]
print("index values :" , arr[index])

where_result = np.where(arr > 5)
print(where_result)
print("where result:" , arr[where_result])



index values : [2 4 6]
(array([5, 6, 7, 8, 9]),)
where result: [ 6  7  8  9 10]


In [16]:
condition_array = np.where(arr>5,True,False)
print(condition_array)

[False False False False False  True  True  True  True  True]


## addition 

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

c = np.concatenate((a,b))
print(c)

c = a*b
print(c)

## COMPATIBILITY
c = a.shape == b.shape
print(c)

[5 7 9]
[1 2 3 4 5 6]
[ 4 10 18]
True


## adding new row and column in matrics

In [23]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
new_col = np.array([[7],[8]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

with_new_column = np.hstack((original,new_col))
print(with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


## deletion

In [ ]:
deleted = np.delete(arr,2)
print(arr)
print(deleted)

arr_2d = np.array([[1,4,6],[4,7,9],[1,8,2]])
deleted_2 = np.delete(arr_2d , [2,5]) ## takes the index of number and deletes it
print(arr_2d)
print(deleted_2)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  4  5  6  7  8  9 10]
[[1 4 6]
 [4 7 9]
 [1 8 2]]
[1 4 4 7 1 8 2]


## inserting and appending

In [31]:
arr = np.array([1,2,3,4]) ## inserts at a particular position
print(arr)
print(np.insert(arr,2,5))
arr_2 = np.array([[1,2],[3,4]])
print(arr_2)
print(np.insert(arr_2,1,[5,6],axis=0))
print(np.insert(arr_2,1,[5,6],axis=1))


print(np.append(arr,[5,6,7,8]))
print(np.append(arr_2,[[5,6],[7,8]]))

[1 2 3 4]
[1 2 5 3 4]
[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
